root: true
plugins:
  - react
  - prettier
  - '@typescript-eslint'
extends:
  - plugin:react/recommended
  - plugin:prettier/recommended
  - plugin:@typescript-eslint/recommended
  - prettier/@typescript-eslint
parser: '@typescript-eslint/parser'
env: {}
rules:
  prettier/prettier:
    - 2
    -
      trailingComma: none
      singleQuote: true
      semi: false
  '@typescript-eslint/no-explicit-any': off
  '@typescript-eslint/explicit-function-return-type': off
